name: emulators_example
description: Runs the emulators package on its own.
publish_to: "none"

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  agentic_emulator:
    path: ../

flutter:
  uses-material-design: false
